name: 'Create a pull request workflow'
description: 'Say "Thank You" to a new pull request'
author: 'Saurabh'

inputs: 
  GITHUB_TOKEN: 
    description: 'Github token'
    required: true 

runs:
  using: 'node12'
  main: 'dist/index.js'