name: Create Request Workflow
on: 
  pull_request:
    types: opened
    branches:
      - feature
jobs:
  jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - run: npm run build